### ISSUE TITLE
cap bias question

### ISSUE THREAD

**Issue by aaronvt** [JQIamo/hv-piezo-driver#1]
could you please say which capacitor/net need to be biased to 2.5V to fix the switch issue

**Comment by npisenti** [comment]
The issue is with the ADG849 switch, which only operates with input voltages between 0V and VDD (our case = 5V). When the capacitor C71 (eagle schematic pg 4) is "disconnected", eg, when you are operating in the high corner frequency mode, the voltage at the common pin of the SPDT switch can swing negative unless you bias it at 2.5V, thereby giving enough overhead. I've attached some pdf screenshots of a QUCS simulation showing this -- let me know if any of it is unclear! But, the problem should've been solved in the schematic as of commit 7b84adf1.

[Switch_Bias_Simulation.pdf](https://github.com/JQIamo/hv-piezo-driver/files/699426/Switch_Bias_Simulation.pdf)

**Comment by aaronvt** [comment]
thanks for the quick response.  I was wondering if thats what you were referring to in the readme

**Comment by npisenti** [comment]
@aaronvt -- it's also worth mentioning that I just pushed a "production" version to github! It's the current `master`, also found at tag v1.2. We just ordered 20 of these boards assembled from Accutrace, who has pretty reasonable prices... (came to ~$136 per board). Still waiting to get them back but if you're interested I can let you know when they're programmed up & integrated into our experiment.

The main change is switching from the old Atmega8 microcontroller to a much nicer 32-bit Cortex-M4 processor (ie, the one used in the Teensy 3.1/3.2 boards). There are also a few other tweaks (like picking off the monitor voltage properly so as to not only mirror the "DC" voltage, but get a true divided version of the output) which might come in handy.

**Comment by aaronvt** [comment]
Neil, that would be great, I was just getting ready to order some.  Did the 136 include fab for the board or just assembly and parts?

**Comment by npisenti** [comment]
The $136 was for fab + assembly, but not parts.

**Comment by aaronvt** [comment]
neil, is the lcd breakout information anywhere?  is it just a cable soldered on the display (im assuming still the NHD-C0216CZ-FSW-FBW-3V3)

**Comment by npisenti** [comment]
There's a breakout board in the mcu-accessories repository (https://github.com/JQIamo/mcu-accessories/blob/master/LCD_Display-euro.brd). You're correct in assuming it uses the NHD display... I'm vaguely remembering though when I assembled the prototype that I still wanted to rotate the connector on the display breakout board by 180 degrees to get the IDC ribbon cable to lie flat, which is cosmetically a little nicer. You might be able to get away with soldering up the display with free-hanging wires, but just note it also requires two 1uF capacitors (which I'm guessing is for some internal DC-DC switching regulator...?)

Incidentally, the populated boards came in yesterday, so this week I'm planning to get the rest of the code working and test them. I'll let you know how it goes!
